#!/bin/sh
echo "Installing hyprpicker"
cd && git clone https://github.com/hyprwm/hyprpicker.git && cd hyprpicker
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target hyprpicker -j`nproc 2>/dev/null || getconf NPROCESSORS_CONF`
sudo cmake --install ./build
cd && sudo rm -rf hyprpicker
