;;; package-lint-flymake-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from package-lint-flymake.el

(autoload 'package-lint-flymake-setup "package-lint-flymake" "\
Setup package-lint integration with Flymake." t)
(register-definition-prefixes "package-lint-flymake" '("package-lint-flymake"))

;;; End of scraped data

(provide 'package-lint-flymake-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; package-lint-flymake-autoloads.el ends here
