#!/bin/bash
# hyprland plugins
hyprpm add https://github.com/VortexCoyote/hyprfocus -v 
hyprpm enable hyprfocus

hyprpm add https://github.com/outfoxxed/hy3 -v
hyprpm enable hy3

hyprpm add https://github.com/KZDKM/Hyprspace -v
hyprpm enable Hyprspace

hyprpm add https://github.com/zakk4223/hyprland-easymotion -v
hyprpm enable hyprEasymotion


