#!/usr/bin/env bash

# Kill already running process
_ps=(waybar swayidle lxpolkit)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Idle
hypridle &

# hotkey daemon
hyprbar &

# wallpaper 
hyprwall &

# theme
hyprtheme &

# plugins 
hyprctl plugin load $HOME/.config/hypr/split-monitor-workspaces.so &

# polkit 
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# Start Apps
#ckb-next &
#QT_QPA_PLATFORM=xcb insync start & 
thunar --daemon &

#xdg-portal-hyprland &

dbus-update-activation-environment --all &
gnome-keyring-daemon -r -d &

gsettings set org.gnome.desktop.interface menus-have-icons true &

emacs --daemon &
