#!/bin/bash
sudo cp -R 01norecommend /etc/apt/apt.conf.d/

sudo apt update && sudo apt install nala zstd
echo "Installing packages"
cd
sudo nala update && sudo nala upgrade
sudo nala install wget curl ckb-next transmission-gtk bat maim python3-pynvim ripgrep tree-sitter-cli fd-find xsel xclip zsh zsh-autosuggestions zsh-syntax-highlighting zoxide fzf rofi dunst bspwm sxhkd papirus-icon-theme ranger gammastep x11-xkb-utils x11-xserver-utils hsetroot xournalpp zathura zathura-pdf-poppler pymol pipx python3-yapf black isort python3-matplotlib  python3-scipy python3-sklearn  python3-biopython python3-pandas aide rng-tools haveged lynis auditd sysstat acct nvidia-dkms-535 xserver-xorg-core xinit network-manager qt5-style-kvantum qt6ct qt5ct btop jgmenu polybar qalculate-gtk

echo "Installing Docker"
# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

# Add the repository to Apt sources:
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin


echo "Installing pacstall & packages"
sudo bash -c "$(curl -fsSL https://pacstall.dev/q/install || wget -q https://pacstall.dev/q/install -O -)"
pacstall -I lsd-deb
pacstall -I neovim
pacstall -I zoom-deb
pacstall -I discord
pacstall -I zotero
pacstall -I insync-deb

echo "Installing emacs"
sudo apt-get build-dep emacs
wget https://gnu.mirror.constant.com/emacs/emacs-29.1.tar.xz
tar -xvf emacs-29.1.tar.xz && cd emacs-29.1 && ./autogen.sh
./configure --with-motif --with-native-compilation --with-modules --with-json --with-mailutils --with-imagemagick --with-tree-sitter --with-xft --with-modules --with-threads --with-harfbuzz --with-sqlite3 --without-jpeg --without-tiff --without-gif --without-png --without-rsvg --without-webp
make -j22
sudo make install && cd

echo "Installing xanmod kernel"
wget -qO - https://dl.xanmod.org/archive.key | sudo gpg --dearmor -o /usr/share/keyrings/xanmod-archive-keyring.gpg
echo 'deb [signed-by=/usr/share/keyrings/xanmod-archive-keyring.gpg] http://deb.xanmod.org releases main' | sudo tee /etc/apt/sources.list.d/xanmod-release.list
sudo apt update && sudo apt install linux-xanmod-x64v3

echo "Setting up Dotfiles"
sudo rm -R ~/.config/
cd && mkdir ~/.config
ln -s $HOME/.dots/.fonts $HOME/
ln -s $HOME/.dots/.themes $HOME/
ln -s $HOME/.dots/gentoo_setup $HOME/
ln -s $HOME/.dots/Projects $HOME/
ln -s $HOME/.dots/.local/bin/bspwm $HOME/.local/bin
ln -s $HOME/.dots/.gtkrc-2.0 $HOME/
ln -s $HOME/.dots/.xinitrc $HOME/
ln -s $HOME/.dots/.Xresources $HOME/
ln -s $HOME/.dots/catppuccin.css $HOME/
ln -s $HOME/.dots/.config/bspwm $HOME/.config/
ln -s $HOME/.dots/.config/btop $HOME/.config/
ln -s $HOME/.dots/.config/ckb-next $HOME/.config/
ln -s $HOME/.dots/.config/dunst $HOME/.config/
ln -s $HOME/.dots/.config/eww $HOME/.config/
ln -s $HOME/.dots/.config/gammastep $HOME/.config/
ln -s $HOME/.dots/.config/gtk-3.0 $HOME/.config/
ln -s $HOME/.dots/.config/gtk-3.0 $HOME/.config/
ln -s $HOME/.dots/.config/jgmenu $HOME/.config/
ln -s $HOME/.dots/.config/Kvantum $HOME/.config/
ln -s $HOME/.dots/.config/lazygit $HOME/.config/
ln -s $HOME/.dots/.config/lsd $HOME/.config/
ln -s $HOME/.dots/.config/lvim $HOME/.config/
ln -s $HOME/.dots/.config/picom $HOME/.config/
ln -s $HOME/.dots/.config/polybar $HOME/.config/
ln -s $HOME/.dots/.config/qalculate $HOME/.config/
ln -s $HOME/.dots/.config/qt5ct $HOME/.config/
ln -s $HOME/.dots/.config/qt6ct $HOME/.config/
ln -s $HOME/.dots/.config/ranger $HOME/.config/
ln -s $HOME/.dots/.config/rofi $HOME/.config/
ln -s $HOME/.dots/.config/suckless $HOME/.config/
ln -s $HOME/.dots/.config/sxhkd $HOME/.config/
ln -s $HOME/.dots/.config/wallpapers $HOME/.config/
ln -s $HOME/.dots/.config/zathura $HOME/.config/
ln -s $HOME/.dots/.config/zsh $HOME/.config/


echo "Setting Up Systemd"
sudo systemctl set-default graphical.target
systemctl --user enable --now wireplumber.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service

cd && mkdir ~/.npm-global && npm config set prefix '~/.npm-global'

curl -fsSL https://fnm.vercel.app/install | sh
curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh)
rm -R $HOME/.zshrc
ln -s $HOME/.dots/.zshrc $HOME/
