#!/bin/sh

echo "Copying Important Files"
sudo rm -rf /etc/apt/sources.list
sudo cp -R $HOME/.dots/parrot-scripts/preconfig_files/kali.list /etc/apt/sources.list.d
sudo cp -R $HOME/.dots/parrot-scripts/preconfig_files/parrot.list /etc/apt/sources.list.d
sudo cp -R $HOME/.dots/parrot-scripts/preconfig_files/parrot-pinning /etc/apt/preferences.d/
sudo cp -R $HOME/.dots/parrot-scripts/preconfig_files/01norecommend /etc/apt/apt.conf.d/
sudo cp -R $HOME/.dots/parrot-scripts/preconfig_files/variables.sh /etc/profile.d/
