#!/bin/sh

echo "Copying Important Files"
sudo cp -R /etc/apt/sources.list /etc/apt/sources.list.d/kali.list
sudo rm -rf /etc/apt/sources.list
sudo cp -R $HOME/.dots/kali-scripts/important_files/sid.list /etc/apt/sources.list.d/
sudo cp -R $HOME/.dots/kali-scripts/important_files/55kali /etc/apt/apt.conf.d/
sudo cp -R $HOME/.dots/kali-scripts/important_files/preferences /etc/apt/
sudo cp -R $HOME/.dots/kali-scripts/important_files/01norecommend /etc/apt/apt.conf.d/
sudo cp -R $HOME/.dots/kali-scripts/important_files/profile /etc/
sudo cp -R $HOME/.dots/kali-scripts/important_files/variables.sh /etc/profile.d/
