#!/bin/sh
flatpak install flathub org.ferdium.Ferdium -y
flatpak install flathub com.bitwarden.desktop -y
flatpak install flathub com.ticktick.TickTick -y
flatpak install flathub com.bitwarden.desktop -y
flatpak install flathub org.onlyoffice.desktopeditors -y
flatpak install flathub com.github.tchx84.Flatseal -y
