#!/bin/sh
cd && sudo -s && cd Downloads && wget https://uk.download.nvidia.com/XFree86/Linux-x86_64/560.31.02/NVIDIA-Linux-x86_64-560.31.02.run
chmod +x NVIDIA-Linux-x86_64-560.31.02.run
./NVIDIA-Linux-x86_64-560.31.02.run
