/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_winicon.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_systray.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "dwmc.h"
#include "focusdir.h"
#include "focusadjacenttag.h"
#include "focusfollowmouse.h"
#include "movestack.h"
#include "roundedcorners.h"
#include "scratchpad.h"
#include "scratchpad_alt_1.h"
#include "seamless_restart.h"
#include "selfrestart.h"
#include "shift.h"
#include "shiftboth.h"
#include "shiftview.h"
#include "shiftviewclients.h"
#ifdef XINERAMA
#include "sortscreens.h"
#endif // XINERAMA
#include "swallow.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_fibonacci.h"
#include "layout_monocle.h"
#include "layout_tile.h"

