/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_winicon.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_systray.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "dragcfact.c"
#include "dwmc.c"
#include "focusadjacenttag.c"
#include "focusdir.c"
#include "focusfollowmouse.c"
#include "movestack.c"
#include "roundedcorners.c"
#include "scratchpad.c"
#include "scratchpad_alt_1.c"
#include "selfrestart.c"
#include "shift.c"
#include "shiftboth.c"
#include "shiftview.c"
#include "shiftviewclients.c"
#ifdef XINERAMA
#include "sortscreens.c"
#endif // XINERAMA
#include "swallow.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "dragmfact.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_fibonacci.c"
#include "layout_monocle.c"
#include "layout_tile.c"

