#!/bin/sh
sudo apt -y install cmake meson ninja-build wayland-utils wayland-protocols libwayland-dev libwlroots-dev libmagic-dev libpango1.0-dev libjpeg-dev

cd && git clone https://github.com/hyprwm/hyprpicker.git && cd hyprpicker

cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target hyprpicker -j$(nproc 2>/dev/null || getconf NPROCESSORS_CONF)

sudo cmake --install ./build
cd && sudo rm -rf hyprpicker
