#!/bin/bash
# hyprland plugins
# hyprpm add https://github.com/VortexCoyote/hyprfocus 
# hyprpm enable /hyprfocus

# hyprpm add https://github.com/outfoxxed/hy3
# hyprpm enable hy3

# hyprpm add https://github.com/KZDKM/Hyprspace
# hyprpm enable Hyprspace

# hyprpm add https://github.com/zakk4223/hyprland-easymotion
# hyprpm enable hyprEasymotion

# Installs cargo pkgs
cargo install --git https://github.com/donovanglover/hyprnome
cargo install --git https://github.com/donovanglover/hyprdim

