#!/bin/sh
cd 
echo "Installing Hyprland"
git clone --recursive https://github.com/hyprwm/Hyprland
cd Hyprland
export CXXFLAGS="-w" # suppress all compiler warnings
meson setup build \
  --wipe \
  --prefix /usr \
  --libexecdir lib \
  --buildtype release \
  --wrap-mode nodownload \
  -D warning_level=0 \
  -D b_lto=true \
  -D b_pie=true \
  -D default_library=shared \
  -D xwayland=enabled \
  -D systemd=enabled

meson compile -C build

sudo meson install -C build 
cd && sudo rm -rf Hyprland 
