#!/bin/sh
echo "Installing wayland-protocols"
cd && git clone --recursive https://gitlab.freedesktop.org/wayland/wayland-protocols.git && cd wayland-protocols
meson _build
ninja -C _build
sudo ninja -C _build install
cd && sudo rm -rf wayland-protocols
