#!/bin/bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCAF35C
sudo cp -R ~/.dots/debian_scripts/scripts/insync.list  /etc/apt/sources.list.d
sudo apt update && sudo apt install insync
