splash = off
ipc = on

preload = ~/.config/wallpapers/tokyonight.jpg

wallpaper = DP-1,~/.config/wallpapers/tokyonight.jpg
wallpaper = DP-2,~/.config/wallpapers/tokyonight.jpg
wallpaper = DP-3,~/.config/wallpapers/tokyonight.jpg
