#!/bin/sh
sudo apt build-dep emacs
cd && wget https://gnu.mirror.constant.com/emacs/emacs-29.4.tar.xz
tar -xvf emacs-29.4.tar.xz && cd emacs-29.4 && ./autogen.sh
./configure --with-pgtk --without-x --with-native-compilation --with-json --with-mailutils --with-imagemagick --with-tree-sitter --with-xft --with-modules --with-threads --with-harfbuzz --with-sqlite3 
make -j22
sudo make install && cd && sudo rm -rf emacs-*
