#!/bin/bash
sudo apt-get install ninja-build gettext cmake unzip curl build-essential
cd && git clone https://github.com/neovim/neovim
cd neovim && git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo -j22
sudo make install && cd && sudo rm -rf neovim
