#!/usr/bin/bash
for pkg in $(<pac-tensorflow)
do 
  pkgctl repo clone --protocol=https $pkg
  cd $pkg
  makepkg -si --skipchecksums --skippgpcheck --nocheck
  cd ..
  sudo rm -rf $pkg
done

# displays package count

# dnf list --installed | awk '{print $1}' | wc -l

# dnf list --installed | wc -l

