#!/bin/sh
echo "Installing ags"
sudo zypper install typescript npm meson gjs-devel gtk3-devel gtk-layer-shell-devel gnome-bluetooth libpulse-devel libdbusmenu-gtk3-devel libsoup-devel pam-devel 
cd
git clone --recursive https://github.com/Aylur/ags.git
cd ags
npm install
meson setup build
sudo meson install -C build
cd && sudo rm -rf ags
