#!/bin/sh
echo "Installing aquamarine"
cd && git clone https://github.com/hyprwm/aquamarine.git && cd aquamarine && git checkout v0.3.0
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`
sudo cmake --install ./build
cd && sudo rm -rf aquamarine 
