#!/bin/sh
cd 
echo "Installing Hyprutils"
git clone https://github.com/hyprwm/hyprutils.git && cd hyprutils
cd hyprutils && git checkout v0.2.1
cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
cmake --build ./build --config Release --target all -j`nproc 2>/dev/null || getconf _NPROCESSORS_CONF`
sudo cmake --install build
cd && sudo rm -rf hyprutils
