#!/bin/sh

echo "Copying Important Files"
sudo rm -rf /etc/apt/sources.list
sudo cp -R $HOME/.dots/debian-scripts/sid.list /etc/apt/sources.list.d/
sudo cp -R $HOME/.dots/debian-scripts/trixie.list /etc/apt/sources.list.d/
sudo cp -R $HOME/.dots/debian-scripts/preferences /etc/apt/
sudo cp -R $HOME/.dots/debian-scripts/01norecommend /etc/apt/apt.conf.d/
sudo cp -R $HOME/.dots/debian-scripts/profile /etc/
sudo cp -R $HOME/.dots/variables.sh /etc/profile.d/
