#!/bin/sh
sudo nala install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3

cd && git clone https://github.com/alacritty/alacritty.git 
cd alacritty && git checkout v0.13.2
cargo build --release --no-default-features --features=wayland
sudo cp target/release/alacritty /usr/local/bin # or anywhere else in $PATH
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database
cd && sudo rm -rf alacritty

