#!/bin/bash
cd && sudo rm -rf ~/.config
cd && mkdir ~/.config
ln -s ~/.dots/.fonts ~/
ln -s ~/.dots/.themes ~/
ln -s ~/.dots/gentoo_setup ~/
ln -s ~/.dots/org ~/
ln -s ~/.dots/.gtkrc-2.0 ~/
ln -s ~/.dots/catppuccin.css ~/
ln -s ~/.dots/.config/starship.toml ~/.config
ln -s ~/.dots/.config/alacritty ~/.config/
ln -s ~/.dots/.config/btop ~/.config/
ln -s ~/.dots/.config/ckb-next ~/.config/
ln -s ~/.dots/.config/gtk-3.0 ~/.config/
ln -s ~/.dots/.config/gtk-4.0 ~/.config/
ln -s ~/.dots/.config/Kvantum ~/.config/
ln -s ~/.dots/.config/lazygit ~/.config/
ln -s ~/.dots/.config/lsd ~/.config/
ln -s ~/.dots/.config/qalculate ~/.config/
ln -s ~/.dots/.config/qt5ct ~/.config/
ln -s ~/.dots/.config/qt6ct ~/.config/
ln -s ~/.dots/.config/ranger ~/.config/
ln -s ~/.dots/.config/wallpapers ~/.config/
ln -s ~/.dots/.config/zathura ~/.config/
ln -s ~/.dots/.config/zsh ~/.config/
ln -s ~/.dots/.config/eww ~/.config/
