#!/bin/sh
echo "Initial Setup"
cd && sudo apt update && sudo apt upgrade && sudo apt reinstall zstd curl gcc make acpid dkms libglvnd-core-dev libglvnd0 libc-dev apt-listchanges needrestart apt-show-versions debsums flatpak
sudo apt update
sudo apt upgrade
sudo apt install gcc make acpid dkms libglvnd-core-dev libglvnd0 libglvnd-dev libc-dev

sudo apt install flatpak
flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
