# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
NTHREADS="22"
source /etc/portage/make.conf.lto
COMMON_FLAGS="-march=native ${CFLAGS} -pipe"
CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 ssse3"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="-C opt-level=3 -C target-cpu=native"
EMERGE_DEFAULT_OPTS="--jobs=10 --keep-going=y --ask"
MAKEOPTS="-j22"
NOCOMMON_OVERRIDE_LIBTOOL="yes"
ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="*"
VIDEO_CARDS="nvidia"
USE="-elogind systemd -gnome -berkdb -kde -ccache -tpm zstd policykit curl \
    -clamav -coreaudio -ios -ipod -ieee1394 -motif gtk pulseaudio qt5 qt6 \
    -emboss -3dfx -altivec -smartcard -ibm wayland -nls -nas pam clang  \
    -neon -nntp -cups -quicktime nvidia sound-server -vim apparmor lto pgo \
    pie gui X upower hardened udev alsa audit dbus tiff jpeg emacs udisks \
    -accessibility -bluetooth -handbook fontconfig truetype opengl keyring"
#RUBY_TARGETS="ruby24 ruby25"
# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C
GRUB_PLATFORMS="efi-64"
